name: Deploy to Netlify

on:
  push:
    branches: 'dev'

permissions:
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: Install dependencies
        run: bun install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          bun run build

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod \
            --json \
            > deploy_output.json

      - name: Get Deploy URL
        id: deploy_url
        run: |
          cat deploy_output.json
          NETLIFY_DEPLOY_URL=$(jq -r '.url' deploy_output.json)
          echo "NETLIFY_DEPLOY_URL=$NETLIFY_DEPLOY_URL" >> "$GITHUB_OUTPUT"

      - name: Comment URL on PR
        uses: actions/github-script@v7
        env:
          NETLIFY_DEPLOY_URL: ${{ steps.url_preview.outputs.NETLIFY_DEPLOY_URL }}
        with:
          script: |
            async function comment(){
            const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            })

            if (!result.data) {
              console.error("No data found.")
              return;
            }

            console.log(result);

            const issueNumber = result.data[0].number
            if(issueNumber){
              await github.rest.issues.createComment({
                issue_number: issueNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'URL: ' + process.env.NETLIFY_PREVIEW_URL
              })
            }else{
              console.log('No PR found for commit ' + context.sha)
              }
            }
            comment()
