name: Deploy to Netlify

# This workflow runs when a PR to dev is closed & merged
# Or when manually triggered.

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - dev

permissions:
  pull-requests: write

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: Install dependencies
        run: bun install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          bun run build

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod \
            --json \
            > deploy_output.json

      - name: Get Deploy URL
        # only needs to run if this was a merged PR
        if: github.event_name == 'pull_request'
        id: deploy_url
        run: |
          NETLIFY_DEPLOY_URL=$(jq -r '.url' deploy_output.json)
          echo "NETLIFY_DEPLOY_URL=$NETLIFY_DEPLOY_URL" >> "$GITHUB_OUTPUT"

      - name: Comment URL on PR
        # only needs to run if this was a merged PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          NETLIFY_DEPLOY_URL: ${{ steps.url_preview.outputs.NETLIFY_DEPLOY_URL }}
        with:
          script: |
            async function comment(){
            const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            })

            if (!result.data) {
              console.error("No PRs found.")
              return;
            }

            const issueNumber = result.data[0].number
            if(issueNumber){
              await github.rest.issues.createComment({
                issue_number: issueNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Deployed to URL: ' + process.env.NETLIFY_DEPLOY_URL
              })
            } else{
              console.log('No PR found for commit ' + context.sha)
              }
            }

            comment()
